### ISSUE TITLE
Set up repo with degree days model

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/hazard#2]
The derivation of degree days indicators from NASA daily downscaled projection (https://www.nasa.gov/nex/gddp/) serves as a worked example for the setting up of the repo. To include in the set-up:
- pipenv for dependency management
- automation of unit tests and code quality using tox via GitHub actions
- README and CONTRIBUTING
For the model itself we want to put in place
- framework for sourcing data
- framework for parallelizing calculation (xarray + Dask)
- instructions for running on JupyterHub to get repeatable results
-

**Comment by joemoorhouse** [comment]
Hi @LucasWouters,
I am working on this at the moment to get a first hazard indicator calculation implemented in a form we are happy with. We then can expand to other issues. I was wondering if this is an issue you might be interested in contributing to also? This could be as simple as reviewing the work so far and offering any suggestions. Thanks, Joe

**Comment by joemoorhouse** [comment]
Hi @reilly335, FYI implementation and documentation for hazard being added with this issue...

**Comment by floriangallo** [comment]
Hi @joemoorhouse , quick question, do we have an issue for the generic 'NASA dataset' hazard calculation? Are we using this one or should we create a specific one to discuss model selection, etc?

**Comment by joemoorhouse** [comment]
Hi @floriangallo, I figure we just use this one, but making sure we can
code it up to reflect its generic nature.
