### ISSUE TITLE
Support accessing NASA NEX CMIP6 using STAC 

### ISSUE THREAD

**Issue by emileten** [os-climate/hazard#36]
Hi @EglantineGiraud @joemoorhouse,

As part of the UK EO data hub (EODH) project, we would like to refactor this repository so as to use STAC as input/output metadata for the hazard data (both input and ouput), rather than using dataset specific [custom code like is being done at the moment](https://github.com/os-climate/hazard/blob/main/src/hazard/sources/nex_gddp_cmip6.py). 

A first step towards this refactoring goal is to update the code so as to access the current input dataset being used (NASA NEX CMIP6) through STAC metadata (that we are going to create for a sample).

Following the 'contribution' documentation and what I am understanding from past PRs, I am going to create a personal fork of this repository and submit a PR to `main` from there.

Any input/comments are very welcome, thank you !

**Comment by joemoorhouse** [comment]
Hi @emileten,

Sounds good! Would definitely be better to use STAC where possible for such inputs. And indeed a PR to main is perfect.

We are converting hazard to use pdm and update Actions in parallel by the way (it is lagging behind the other repos) but should not affect your change too much.

Thanks,
Joe
